export const projects = [
  {
    title: 'LuxFlo',
    description: "LuxFlo is an Algorand based blockchain platform to create escrow agreements on short-term rentals of luxury goods. The buyer deposits escrow money into a smart contract, and both parties can solicit on-chain arbitration through a trusted third party.",
    image: '/images/1.png',
    tags: ['Next', 'Node', 'TEALScript', 'Algorand'],
    source: 'https://github.com/LuxFlo/luxflo-frontend',
    visit: 'https://luxflo-fe.vercel.app/',
    id: 0,
  },
  {
    title: 'HobbyFlo',
    description:"HobbyFlo lets Ethereum users secure short-term rentals through escrow smart contracts and resolve disputes through an ai empowered arbiter.",
    image: '/images/2.png',
    tags: ['Polygon', 'Solidity', 'Next', 'TypeScript', 'Ethers.js'],
    source: 'https://github.com/HobbyFlo-ethmiami2023/HobbyFlo-ethmiami2023',
    visit: 'https://hobby-flo.vercel.app/',
    id: 1,
  },
  {
    title: 'DECEnergy.xyz',
    description: "DECEnergy.xyz is a decentralized investment platform model for users to invest in renewable energy projects. An ERC-1155 Token is used to represent shares of a solar energy installation.",
    image: '/images/3.png',
    tags: ['Typescript', 'Solidity', 'Ethers.js', 'Svelte.js'],
    source: 'https://github.com/nickmura/decsolar-energy',
    visit: 'https://decenergy.xyz/',
    id: 2,
  },
  {
    title: 'Badges',
    description: "Badges is a decentralized app which lets companies track helpful discussion in forums and documentation. Employees can earn NFT badges for their contributions, and companies can token gate rewards according to the badges.",
    image: '/images/4.png',
    tags: ['Solidity', 'Goerli', 'Alchemy', 'Next.js'],
    source: 'https://github.com/patrickbdevaney/front-end-pennh',
    visit: 'https://front-end-pennh.vercel.app/',
    id: 3,
  },
  {
    title: 'Mixed Reality Giant Chess',
    description: "Mixed Reality Giant Chess is a unity game which leverages MRTK-3 to create a holographic chess game you can play in your living room.",
    image: '/images/chess.jpg',
    tags: ['C#', 'Unity', 'MRTK-3', 'Microsoft HoloLens 3'],
    source: 'https://github.com/shurtado12/ShellHacks2022',
    visit: 'https://www.youtube.com/watch?v=pDe5CFj7W9w',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];